"""
Build data.yaml + train/val/test txt lists WITHOUT copying files.
YOLO reads paths from txt files directly. Fast, low memory.

Output:
    data/datasets/final_v3/
    ├── data.yaml
    ├── train.txt   (paths)
    ├── valid.txt
    └── test.txt
"""
import random
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ROBOFLOW = Path("/Users/sertacakalin/Desktop/istanbul-traffic-vehicles")
AUTO = PROJECT_ROOT / "data/datasets/auto_labeled"
OUT = PROJECT_ROOT / "data/datasets/final_v3"

CLASSES = ["bus", "car", "motorcycle", "truck"]
SEED = 42

OUT.mkdir(parents=True, exist_ok=True)

# Collect all image paths (with verified labels)
images = []

# Roboflow: train/images/*.jpg → train/labels/*.txt
for img in (ROBOFLOW / "train/images").glob("*.jpg"):
    lbl = ROBOFLOW / "train/labels" / f"{img.stem}.txt"
    if lbl.exists():
        images.append(str(img.resolve()))

print(f"Roboflow: {len(images)}")

# Auto-labeled: 4 folders
for folder in ["file1_night", "file2_dense", "file3_day", "file4_evening"]:
    src = AUTO / folder / "images"
    lbl_dir = AUTO / folder / "labels"
    count_before = len(images)
    for img in src.glob("*.jpg"):
        lbl = lbl_dir / f"{img.stem}.txt"
        if lbl.exists():
            images.append(str(img.resolve()))
    print(f"{folder}: {len(images) - count_before}")

print(f"\nToplam: {len(images)}")

# Shuffle + split
random.seed(SEED)
random.shuffle(images)
n = len(images)
train_end = int(n * 0.70)
val_end = int(n * 0.90)

splits = {
    "train": images[:train_end],
    "valid": images[train_end:val_end],
    "test": images[val_end:],
}

for name, paths in splits.items():
    txt = OUT / f"{name}.txt"
    txt.write_text("\n".join(paths))
    print(f"{name}.txt: {len(paths)} paths")

# data.yaml — txt path list format
yaml_content = f"""# Final dataset using path lists (no files copied)
# Generated by scripts/build_path_lists.py

path: {OUT}
train: train.txt
val:   valid.txt
test:  test.txt

nc: {len(CLASSES)}
names: {CLASSES}
"""
(OUT / "data.yaml").write_text(yaml_content)
print(f"\ndata.yaml written")
print(f"Output: {OUT}")
